/**
 * This file is responsible for managing the users in a group.
 * it includes functionality to create new users, assign them to a group, and 
 * remove them from a group.
 * This file is fully generated by Copilot, with different prompts.
 */

import React, { useEffect, useState } from "react";
import PropTypes from "prop-types"; // Import PropTypes
import API from "../api";
import "./UsersPanel.css"; // Add CSS for styling

/**
 * UsersPanel component for managing users in a group.
 */
function UsersPanel({ groupId }) {
    const [users, setUsers] = useState([]);
    const [allUsers, setAllUsers] = useState([]);
    const [selectedUser, setSelectedUser] = useState(null); // Track the selected user
    const [newUserName, setNewUserName] = useState("");
    const [newUserEmail, setNewUserEmail] = useState("");
    const [newUserPassword, setNewUserPassword] = useState("");
    const [selectedUserId, setSelectedUserId] = useState("");
    const [selectedRole, setSelectedRole] = useState("member"); // Default role is "member"

    useEffect(() => {
        if (groupId) {
            // Fetch users in the group
            API.get(`/groups/${groupId}/users/`)
                .then((response) => {
                    console.log("Fetched users in group:", response.data); // Debug log
                    setUsers(response.data || []);
                })
                .catch((error) => console.error("Error fetching users in group:", error));
        }

        // Fetch all users for the dropdown
        API.get("/users/")
            .then((response) => {
                console.log("Fetched all users:", response.data); // Debug log
                setAllUsers(response.data || []);
            })
            .catch((error) => console.error("Error fetching all users:", error));
    }, [groupId]);

    /**
     * Handles the creation of a new user.
     * Validates the input fields and sends a POST request to create the user.
     */
    const handleAddUser = () => {
        if (!newUserName.trim()) {
            alert("User name is required.");
            return;
        }
        if (!newUserEmail.trim()) {
            alert("User email is required.");
            return;
        }
        if (!newUserPassword.trim()) {
            alert("User password is required.");
            return;
        }

        const payload = {
            name: newUserName,
            email: newUserEmail,
            password: newUserPassword,
        };

        console.log("Creating user with payload:", payload); // Debug log

        API.post("/users/", payload)
            .then((response) => {
                console.log("User created successfully:", response.data); // Debug log
                setAllUsers((prevUsers) => [...prevUsers, response.data]);
                setNewUserName("");
                setNewUserEmail("");
                setNewUserPassword("");
            })
            .catch((error) => {
                console.error("Error creating user:", error.response?.data || error.message);
                alert(error.response?.data?.error || "Failed to create user. Please try again.");
            });
    };

    /**
     * Handles assigning a user to the group.
     * Validates the selected user and role, then sends a POST request to assign the user.
     */
    const handleAssignUserToGroup = () => {
        if (!selectedUserId) {
            alert("Please select a user to assign to the group.");
            return;
        }

        const payload = { unique_user: selectedUserId, role: selectedRole };

        console.log("Assigning user to group:", { groupId, payload });

        API.post(`/groups/${groupId}/users/`, payload)
            .then((response) => {
                console.log("User assigned successfully:", response.data);
                setUsers((prevUsers) => [...prevUsers, response.data]);
                setSelectedUserId("");
                setSelectedRole("member");
            })
            .catch((error) => {
                console.error("Error assigning user to group:", error.response?.data || error.message);
                alert(error.response?.data?.error || "Failed to assign user to group. Please try again.");
            });
    };

    /**
     * Handles removing a user from the group.
     * Prompts for confirmation and sends a DELETE request to remove the user.
     */
    const handleRemoveUserFromGroup = (uniqueUserId) => {
        if (!window.confirm("Are you sure you want to remove this user from the group?")) return;

        console.log("Removing user from group:", { groupId, uniqueUserId });

        API.delete(`/groups/${groupId}/users/${uniqueUserId}/`)
            .then(() => {
                console.log("User removed successfully:", uniqueUserId);
                setUsers((prevUsers) => prevUsers.filter((user) => user.unique_user !== uniqueUserId));
                setSelectedUser(null); // Close the modal after removal
            })
            .catch((error) => {
                console.error("Error removing user from group:", error.response?.data || error.message);
                alert(error.response?.data?.error || "Failed to remove user from group. Please try again.");
            });
    };

    /**
     * Handles selecting a user to view their details.
     */
    const handleUserClick = (user) => {
        setSelectedUser(user);
    };

    // Add this useEffect to log the updated selectedUser
    useEffect(() => {
        if (selectedUser) {
            console.log("Selected user:", selectedUser);
        }
    }, [selectedUser]);

    /**
     * Closes the user details modal.
     */
    const handleCloseDetails = () => {
        setSelectedUser(null); // Clear the selected user
    };

    return (
        <div className="users-panel">
            <h2>Users in Group</h2>
            <ul className="user-list">
                {users.length > 0 ? (
                    users.map((user) => (
                        <li
                            key={user.unique_user} // Use unique_user as the key
                            className="user-item"
                            onClick={() => handleUserClick(user)} // Handle user click
                        >
                            <span className="user-name">{user.name}</span>
                            <span className="user-role">{user.role}</span>
                        </li>
                    ))
                ) : (
                    <p>No users in this group.</p>
                )}
            </ul>

            {/* User Details Modal */}
            {selectedUser && (
                <div className="modal">
                    <div className="modal-content">
                        <h3>User Details</h3>
                        <p><strong>Name:</strong> {selectedUser.name}</p>
                        <p><strong>Email:</strong> {selectedUser.email}</p>
                        <p><strong>Role:</strong> {selectedUser.role}</p>
                        <button
                            className="delete-button"
                            onClick={() => handleRemoveUserFromGroup(selectedUser.unique_user)} // Use unique_user here
                        >
                            Remove User from Group
                        </button>
                        <button className="close-button" onClick={handleCloseDetails}>
                            Close
                        </button>
                    </div>
                </div>
            )}

            <div className="add-user">
                <h3>Create New User</h3>
                <input
                    type="text"
                    placeholder="Name"
                    value={newUserName}
                    onChange={(e) => setNewUserName(e.target.value)}
                />
                <input
                    type="email"
                    placeholder="Email"
                    value={newUserEmail}
                    onChange={(e) => setNewUserEmail(e.target.value)}
                />
                <input
                    type="password"
                    placeholder="Password"
                    value={newUserPassword}
                    onChange={(e) => setNewUserPassword(e.target.value)}
                />
                <button onClick={handleAddUser}>Add User</button>
            </div>

            <div className="assign-user">
                <h3>Assign User to Group</h3>
                <select
                    value={selectedUserId}
                    onChange={(e) => setSelectedUserId(e.target.value)}
                >
                    <option value="">Select User</option>
                    {allUsers.map((user) => (
                        <option key={user.unique_user} value={user.unique_user}>
                            {user.name}
                        </option>
                    ))}
                </select>
                <select
                    value={selectedRole}
                    onChange={(e) => setSelectedRole(e.target.value)}
                >
                    <option value="Project Manager">Project Manager</option>
                    <option value="admin">Admin</option>
                    <option value="Business Analyst">Business Analyst</option>
                    <option value="Technical Leader">Technical Leader</option>
                    <option value="Summer Trainee">Summer Trainee</option>
                    <option value="HR">HR</option>
                </select>
                <button onClick={handleAssignUserToGroup}>Assign to Group</button>
            </div>
        </div>
    );
}

// Define PropTypes for the component
UsersPanel.propTypes = {
    groupId: PropTypes.string.isRequired, // Validate groupId as a required string
};

export default UsersPanel;